
# Homepage visible information
[homeInfoParams]
Title = "[~]$ whoami?"
Content = """
Hey, I’m Prajwal (praj-mkdir). I build backend systems, secure cloud infrastructure, and explore the space where DevOps meets security."""

[[socialIcons]]
name = "linkedin"
url = "https://www.linkedin.com/in/prajwalspatil/"

[[socialIcons]]
name = "email"
url = "mailto:praj2patil9@gmail.com"

[[socialIcons]]
name = "github"
url = "https://github.com/praj-mkdir/"

[[socialIcons]]
name = "Contact Me"
url = "/contact"
