name: Publish to GH Pages

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source (main branch)
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.146.0'
          extended: true

      - name: Build
        run: hugo

      - name: Prepare git-pages branch
        if: github.ref == 'refs/heads/main'
        run: |
          mkdir built-site
          cd built-site
          git init
          git remote add origin https://github.com/${{ github.repository }}
          git fetch origin git-pages
          git checkout -b git-pages origin/git-pages || git checkout -b git-pages

      - name: Deploy to git-pages
        if: github.ref == 'refs/heads/main'
        run: |
          cp -R public/* built-site/
          cd built-site
          git add .

          if git diff --cached --quiet; then
            echo "No changes to commit. Skipping deployment."
            exit 0
          fi

          git config user.name 'github-actions[bot]'
          git config user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git commit -m 'Updated site'
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} HEAD:git-pages
