name: Publish to GH Pages

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source (main branch)
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Checkout destination (git-pages branch)
        if: github.ref == 'refs/heads/main'
        uses: actions/checkout@v3
        with:
          ref: git-pages
          path: built-site

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.146.0'
          extended: true

      - name: Build
        run: hugo

      - name: Deploy to git-pages
        if: github.ref == 'refs/heads/main'
        run: |
          cp -R public/* ${GITHUB_WORKSPACE}/built-site/
          cd ${GITHUB_WORKSPACE}/built-site
          git add .

          # Skip commit if nothing has changed
          if git diff --cached --quiet; then
            echo "No changes to commit. Skipping deployment."
            exit 0
          fi

          git config user.name 'github-actions[bot]'
          git config user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git commit -m 'Updated site'
          git push
